import argparse
import time

import numpy as np
import serial

import drawing
from demo import Hand


def _split_strokes(strokes):
    """Split an Nx3 stroke array into polylines using eos markers."""
    polylines = []
    current = []
    for x, y, eos in strokes:
        current.append((float(x), float(y)))
        if eos == 1.0:
            if len(current) >= 2:
                polylines.append(np.array(current, dtype=np.float64))
            current = []
    if len(current) >= 2:
        polylines.append(np.array(current, dtype=np.float64))
    return polylines


def _prepare_line_strokes(offsets, line_index, line_height=60.0, view_width=1000.0):
    """Apply the same transforms used by demo._draw and return line polylines."""
    local_offsets = np.copy(offsets)
    local_offsets[:, :2] *= 1.5

    strokes = drawing.offsets_to_coords(local_offsets)
    strokes = drawing.denoise(strokes)
    strokes[:, :2] = drawing.align(strokes[:, :2])

    strokes[:, 1] *= -1
    initial_coord = np.array([0.0, -(3.0 * line_height / 4.0) - line_index * line_height])
    strokes[:, :2] -= strokes[:, :2].min() + initial_coord
    strokes[:, 0] += (view_width - strokes[:, 0].max()) / 2.0

    return _split_strokes(strokes)


def _build_layout(stroke_lines):
    """Combine line polylines into one list and return path bounds."""
    all_polylines = []
    min_x = None
    min_y = None
    max_x = None
    max_y = None

    for line_strokes in stroke_lines:
        for poly in line_strokes:
            all_polylines.append(poly)
            xs = poly[:, 0]
            ys = poly[:, 1]
            p_min_x = float(xs.min())
            p_max_x = float(xs.max())
            p_min_y = float(ys.min())
            p_max_y = float(ys.max())
            min_x = p_min_x if min_x is None else min(min_x, p_min_x)
            max_x = p_max_x if max_x is None else max(max_x, p_max_x)
            min_y = p_min_y if min_y is None else min(min_y, p_min_y)
            max_y = p_max_y if max_y is None else max(max_y, p_max_y)

    if not all_polylines:
        raise ValueError("No drawable polylines were generated.")

    return all_polylines, (min_x, min_y, max_x, max_y)


def _scale_to_bed(polylines, bounds, origin_x, origin_y, max_width, max_height, margin, flip_y=False):
    min_x, min_y, max_x, max_y = bounds
    width = max(max_x - min_x, 1e-6)
    height = max(max_y - min_y, 1e-6)

    usable_width = max_width - 2.0 * margin
    usable_height = max_height - 2.0 * margin
    if usable_width <= 0.0 or usable_height <= 0.0:
        raise ValueError("Margins are too large for the selected drawing area.")

    scale = min(usable_width / width, usable_height / height)
    scaled_polylines = []

    for poly in polylines:
        transformed = np.copy(poly)
        transformed[:, 0] = (transformed[:, 0] - min_x) * scale + origin_x + margin
        transformed[:, 1] = (transformed[:, 1] - min_y) * scale + origin_y + margin
        if flip_y:
            y0 = origin_y + margin
            y1 = origin_y + margin + height * scale
            transformed[:, 1] = y1 - (transformed[:, 1] - y0)
        scaled_polylines.append(transformed)

    return scaled_polylines


def _simplify_polyline(polyline, min_segment_mm):
    """Drop points that are closer than min_segment_mm to reduce serial traffic."""
    if len(polyline) < 3:
        return polyline

    kept = [polyline[0]]
    last = polyline[0]
    threshold_sq = min_segment_mm * min_segment_mm

    for point in polyline[1:-1]:
        dx = point[0] - last[0]
        dy = point[1] - last[1]
        if dx * dx + dy * dy >= threshold_sq:
            kept.append(point)
            last = point

    kept.append(polyline[-1])
    return np.array(kept, dtype=np.float64)


def _generate_gcode(
    polylines,
    draw_feed,
    travel_feed,
    z_up,
    z_down,
    z_feed,
    home,
    park_x,
    park_y,
):
    gcode = []
    gcode.append("; Handwriting trace generated by marlin_trace.py")
    gcode.append("G21")
    gcode.append("G90")
    if home:
        gcode.append("G28")
    gcode.append("G1 Z{:.3f} F{:.0f}".format(z_up, z_feed))

    for poly in polylines:
        start = poly[0]
        gcode.append("G0 X{:.3f} Y{:.3f} F{:.0f}".format(start[0], start[1], travel_feed))
        gcode.append("G1 Z{:.3f} F{:.0f}".format(z_down, z_feed))
        for point in poly[1:]:
            gcode.append("G1 X{:.3f} Y{:.3f} F{:.0f}".format(point[0], point[1], draw_feed))
        gcode.append("G1 Z{:.3f} F{:.0f}".format(z_up, z_feed))

    gcode.append("G0 X{:.3f} Y{:.3f} F{:.0f}".format(park_x, park_y, travel_feed))
    gcode.append("M400")
    return gcode


class MarlinSerialSender(object):

    def __init__(self, port, baud, timeout):
        self._serial = serial.Serial(port=port, baudrate=baud, timeout=timeout)

    def initialize(self):
        time.sleep(2.0)
        self._serial.reset_input_buffer()
        self._serial.reset_output_buffer()
        self._serial.write(b"\n\n")
        self._serial.flush()
        time.sleep(0.5)
        self._drain_until_idle(max_reads=50)
        self.send("M115")

    def close(self):
        self._serial.close()

    def send(self, command, require_ok=True, max_wait_seconds=30.0):
        stripped = command.strip()
        if not stripped or stripped.startswith(";"):
            return
        payload = (stripped + "\n").encode("ascii")
        self._serial.write(payload)
        self._serial.flush()

        if not require_ok:
            return

        started = time.time()
        lines = []
        while (time.time() - started) <= max_wait_seconds:
            raw = self._serial.readline()
            if not raw:
                continue
            line = raw.decode("utf-8", errors="ignore").strip()
            if not line:
                continue
            lines.append(line)
            lower = line.lower()
            if lower.startswith("error") or "!!" in line:
                raise RuntimeError("Marlin reported an error for '{}': {}".format(command, line))
            if lower == "ok" or lower.startswith("ok "):
                return

        raise RuntimeError(
            "Timed out waiting for Marlin response to '{}'. Last lines: {}".format(
                command,
                lines[-5:]
            )
        )

    def _drain_until_idle(self, max_reads=50):
        for _ in range(max_reads):
            raw = self._serial.readline()
            if not raw:
                break


def _build_biases(lines, bias_value):
    return [bias_value for _ in lines]


def _build_styles(lines, style):
    if style is None:
        return None
    return [style for _ in lines]


def parse_args():
    parser = argparse.ArgumentParser(description="Generate handwriting and trace it on a Marlin printer over serial.")
    parser.add_argument("--text", nargs="+", required=True, help="Text lines to render. Use multiple quoted items for multiple lines.")
    parser.add_argument("--style", type=int, default=9, help="Style index to prime with. Use -1 to disable priming.")
    parser.add_argument("--bias", type=float, default=0.75, help="Sampling bias.")
    parser.add_argument("--port", default="COM3", help="Serial port for Marlin.")
    parser.add_argument("--baud", type=int, default=115200, help="Serial baud rate.")
    parser.add_argument("--serial-timeout", type=float, default=1.0, help="Serial read timeout in seconds.")
    parser.add_argument("--origin-x", type=float, default=10.0, help="Drawing area origin X in mm.")
    parser.add_argument("--origin-y", type=float, default=10.0, help="Drawing area origin Y in mm.")
    parser.add_argument("--max-width", type=float, default=200.0, help="Max drawing width in mm.")
    parser.add_argument("--max-height", type=float, default=200.0, help="Max drawing height in mm.")
    parser.add_argument("--margin", type=float, default=5.0, help="Inner margin inside drawing area in mm.")
    parser.add_argument("--flip-y", action="store_true", help="Flip Y coordinates in case your rig is mirrored.")
    parser.add_argument("--draw-feed", type=float, default=1200.0, help="Drawing feedrate in mm/min.")
    parser.add_argument("--travel-feed", type=float, default=3000.0, help="Travel feedrate in mm/min.")
    parser.add_argument("--z-up", type=float, default=5.0, help="Pen-up Z height.")
    parser.add_argument("--z-down", type=float, default=0.0, help="Pen-down Z height.")
    parser.add_argument("--z-feed", type=float, default=600.0, help="Z axis feedrate in mm/min.")
    parser.add_argument("--min-segment", type=float, default=0.2, help="Minimum point spacing in mm.")
    parser.add_argument("--no-home", action="store_true", help="Skip G28 homing.")
    parser.add_argument("--park-x", type=float, default=0.0, help="Final park X in mm.")
    parser.add_argument("--park-y", type=float, default=0.0, help="Final park Y in mm.")
    parser.add_argument("--gcode-out", default="", help="Optional file path to save generated G-code.")
    parser.add_argument("--dry-run", action="store_true", help="Generate and optionally save G-code without sending to printer.")
    return parser.parse_args()


def main():
    args = parse_args()

    lines = args.text
    styles = None if args.style < 0 else _build_styles(lines, args.style)
    biases = _build_biases(lines, args.bias)

    hand = Hand()
    sampled_offsets = hand._sample(lines, biases=biases, styles=styles)

    stroke_lines = []
    for i, offsets in enumerate(sampled_offsets):
        stroke_lines.append(_prepare_line_strokes(offsets, line_index=i))

    polylines, bounds = _build_layout(stroke_lines)
    polylines = _scale_to_bed(
        polylines=polylines,
        bounds=bounds,
        origin_x=args.origin_x,
        origin_y=args.origin_y,
        max_width=args.max_width,
        max_height=args.max_height,
        margin=args.margin,
        flip_y=args.flip_y,
    )
    polylines = [_simplify_polyline(p, args.min_segment) for p in polylines]

    gcode = _generate_gcode(
        polylines=polylines,
        draw_feed=args.draw_feed,
        travel_feed=args.travel_feed,
        z_up=args.z_up,
        z_down=args.z_down,
        z_feed=args.z_feed,
        home=not args.no_home,
        park_x=args.park_x,
        park_y=args.park_y,
    )

    if args.gcode_out:
        with open(args.gcode_out, "w") as fp:
            fp.write("\n".join(gcode) + "\n")

    print("Prepared {} polylines and {} G-code commands.".format(len(polylines), len(gcode)))

    if args.dry_run:
        print("Dry run requested; not sending to printer.")
        return

    sender = MarlinSerialSender(port=args.port, baud=args.baud, timeout=args.serial_timeout)
    try:
        sender.initialize()
        for index, command in enumerate(gcode):
            sender.send(command, require_ok=True)
            if (index + 1) % 100 == 0:
                print("Sent {}/{} commands".format(index + 1, len(gcode)))
    finally:
        sender.close()

    print("Done. Handwriting trace sent to {}.".format(args.port))


if __name__ == "__main__":
    main()
